### ISSUE TITLE
Request examples stopped working in version 3.3.1 

### ISSUE THREAD

**Issue by rasmusoh** [mattfrear/Swashbuckle.Examples#10]
Hi!

I just updated my Swashbuckle.Examples package to version 3.3.1 from version 3.3.0, and the request examples are no longer displaying correctly, instead they revert back to the default examples.

using 3.3.0:
![image](https://user-images.githubusercontent.com/7687216/30115104-08d526ce-931a-11e7-9b05-7e7a5ab7bf69.png)

using 3.3.1:
![image](https://user-images.githubusercontent.com/7687216/30115278-8dc1d972-931a-11e7-8a9c-63ce7d42283e.png)

The controller look something like
```
        [HttpPost]
        [SwaggerResponse(HttpStatusCode.OK, "Returns payment registration response", typeof(MyResponse<RegisterPaymentResponse>))]
        [SwaggerRequestExample(typeof(MyRequest<RegisterPaymentRequest>), typeof(RegisterPaymentExample))]
        [Route("payments/")]
        public async Task<IHttpActionResult> RegisterPayment([FromBody] MyRequest<RegisterPaymentRequest> registerPaymentRequest)
```

It only seems to happen for generic request classes, if I change the controller to 
```
        [HttpPost]
        [SwaggerResponse(HttpStatusCode.OK, "Returns payment registration response", typeof(MyResponse<RegisterPaymentResponse>))]
        [SwaggerRequestExample(typeof(RegisterPaymentRequest), typeof(RegisterPaymentExample))]
        [Route("payments/")]
        public async Task<IHttpActionResult> RegisterPayment([FromBody] RegisterPaymentRequest registerPaymentRequest)
```

it starts working again.

**Comment by mattfrear** [comment]
Oh no, sorry about that.
What version of Swashbuckle do you have installed?

**Comment by rasmusoh** [comment]
I am using version 5.6.0. Tried updating to 3.3.1 on a different service running Swashbuckle 5.5.3, same problem there...

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.Examples/3.3.2
