### ISSUE TITLE
Any jsonConverter in SwaggerRequestExample override WebApiConfig in v3.3.1

### ISSUE THREAD

**Issue by KennethWKZ** [mattfrear/Swashbuckle.Examples#11]
As title, when I'm trying to add StringEnumConverter into SwaggerRequestExample  it will override my global JsonSerializerSettings in WebApiConfig. Is there anyway to avoid this to override global settings and make it independently.

**Comment by mattfrear** [comment]
Hmm that sounds unlikely, it shouldn't do that. I will investigate when I get a chance

**Comment by mattfrear** [comment]
Hmm, you're right. I will see if I can come up with a fix. In the meantime, if this is causing you problems, then perhaps downgrade to version 3.0.0 of this package.

**Comment by KennethWKZ** [comment]
Is ok for me, just temporary don't use json converter in swagger request example and it will be fine.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.Examples/3.3.2
