### ISSUE TITLE
IExampleProvider ignored when same class is used in SwaggerRequestExample

### ISSUE THREAD

**Issue by HansOlavS** [mattfrear/Swashbuckle.Examples#12]
If you have more than one method that uses the same request class but with different IExampleProviders. The result is that only one of them is used on both methods.

```csharp
public class MessageController : Controller
{
  [HttpPost]
  [SwaggerRequestExample(requestType: typeof(MessageRequest), examplesProviderType: typeof(MessageExampleProvider))]
  public IActionResult PostMessage([FromBody] MessageRequest message)
  {
    return new OkResult();
  }

  [HttpPost]
  [SwaggerRequestExample(requestType: typeof(MessageRequest), examplesProviderType: typeof(MessageExampleProvider2))]
  public IActionResult PostMessage2([FromBody] MessageRequest message)
  {
    return new OkResult();
  }
}
```

In this example I'm not able to get PostMessage2 to use the MessageExampleProvider2 in swagger.
Is this a bug or am I using it incorrectly?

**Comment by mattfrear** [comment]
Hi
What you are trying to do can't be done, as it is a limitation of the [Swagger 2.0 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) (I think).

If you open the swagger document when you run your api (it's located at /swagger/docs/v1), you will see that each of your PostMessage and PostMessage2 are under the "paths" entry.  You'll see your MessageRequest under parameters, and you'll see that the schema of MessageRequest points to $ref": "#/definitions/MessageRequest".

If you scroll to the bottom of the doc you should see #/definitions/MessageRequest - it has an examples property - that is what my library populates, and there is only space for one example.

If you really want to do this you would have to create a MessageRequest2 object, which is probably undesirable.

**Comment by HansOlavS** [comment]
Thanks Matt! Love the library BTW. I suspected this was a limitation in swashbuckle/swagger itself. And thanks for the quick response :)
