### ISSUE TITLE
DescriptionOperationFilter Null Exception

### ISSUE THREAD

**Issue by imukai** [mattfrear/Swashbuckle.Examples#15]
Having a SwaggerResponse attribute without a response type model seems to cause a NullReferenceException in your DescriptionOperationFilter on line 31 as attr.Type is null.

Example:
`[SwaggerResponse(HttpStatusCode.Forbidden, "User failed authentication..")]`

> 500 : {"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException",
> "StackTrace":" at Swashbuckle.Examples.DescriptionOperationFilter.SetResponseModelDescriptions(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)\r\n 
> at Swashbuckle.Examples.DescriptionOperationFilter.Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)\r\n 
> at Swashbuckle.Swagger.SwaggerGenerator.CreateOperation(ApiDescription apiDesc, SchemaRegistry schemaRegistry)\r\n 
> at Swashbuckle.Swagger.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry)\r\n 
> at Swashbuckle.Swagger.SwaggerGenerator.<>c__DisplayClass7.<GetSwagger>b__4(IGrouping`2 group)\r\n
> snip...

**Comment by imukai** [comment]
My fix is to just insert this at the beginning of your foreach on line 23.  Not going to bother with a pull request for a single line - and maybe you want to handle it in a different manner.

`if (attr.Type == null) continue;`

**Comment by mattfrear** [comment]
Well spotted, thanks 👍

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.Examples/3.3.4
