### ISSUE TITLE
DescriptionOperationFilter:  Child Properties Ignored

### ISSUE THREAD

**Issue by imukai** [mattfrear/Swashbuckle.Examples#16]
The DescriptionOperationFilter only goes one level deep when looking for descriptions.  If you have a custom datatype as a property, with Description attributes on that datatype's properties, they will not be retrieved.

small example:

```
public class Pet {
  [Description("This is fine")]
  public string Name {get; set;}
  
  [Description("This is also fine.")]
  public Owner Master {get; set;}
}
```

```
public class Owner {
  [Description("This will not be seen.")]
  public string Name {get; set;}
}
```

If you use XML Comments instead of the attribute, it picks up the child properties just fine - figure that's Swashbuckle doing it though.  I personally prefer using Description because there's less visual clutter in the file.

This one may be more of a headache to resolve and I can send you a quick and dirty fix tomorrow morning if you need help figuring out a recursive function.

**Comment by imukai** [comment]
Well apparently my employer blocks open Git operations so I can't push anything to my own fork for a pull request.  I'll see if I can attach my code file to this comment.

I moved part of your code into a recursive function and added logic to go into child properties and recurse.  It is quick and dirty as I said.  

While it works, I haven't done any testing for use cases beyond what I described in the initial post.  You may want to do some due diligence and decide if it can be handled better to cover more cases.

[Description.txt](https://github.com/mattfrear/Swashbuckle.Examples/files/1324475/Description.txt)

**Comment by mattfrear** [comment]
Hi @imukai 
I haven't had a chance to look at your PR yet, but your comment

> If you use XML Comments instead of the attribute, it picks up the child properties just fine - figure that's Swashbuckle doing it though.

I wonder if my filter should exist at all, if there is already a Swashbuckle supported way of doing this. How exactly is that done in Swashbuckle?

I'm considering rewriting my filters TDD style so that they have tests, but finding the time to do that is difficult.

Anyway, thanks for your contribution. I'm not sure what to do with it right now.

**Comment by mattfrear** [comment]
Published https://www.nuget.org/packages/Swashbuckle.Examples/3.4.0
