### ISSUE TITLE
Explicit error on wrong IExamplesProvider Type

### ISSUE THREAD

**Issue by ThibaultLemaire** [mattfrear/Swashbuckle.Examples#17]
To help build consistent examples quickly, I wrote an `IExamplesProvider` based on the `Fixture` class from Ploeh's AutoFixture library.

Basically I can decorate my methods with something like this :

``` C#
[SwaggerResponseExample(HttpStatusCode.OK, typeof(AutoExample<IEnumerable<DateTime>>))]
```

But then as one of my coworkers wrote a new method, he forgot the `AutoExample` which is the class that does the magic. So we ended up with this instead :

``` C#
[SwaggerResponseExample(HttpStatusCode.OK, typeof(IEnumerable<DateTime>))]
```

and our code failed with "Cannot create an instance of an interface". Although it didn't take us that much to time find the problem, we could have found it quicker with a more explicit error.

The problem is that when the `ExamplesProviderType` doesn't implement `IExamplesProvider`, that code fails with an invalid cast exception :

``` C#
var provider = (IExamplesProvider)Activator.CreateInstance(attr.ExamplesProviderType);
```

but as you can see, when that Type is an interface, it actually breaks before the cast ; At `Activator.CreateInstance()`.

So my suggestion would be to throw an exception earlier, maybe right at the Attribute level (`SwaggerResponseExampleAttribute` and `SwaggerRequestExampleAttribute`), if the type isn't an `IExamplesProvider`. Which of course I can do if you want me to.

**Comment by mattfrear** [comment]
Hi Thibault,

Sounds like a great suggestion, so a PR is welcome 👍
