### ISSUE TITLE
Json properties's case type

### ISSUE THREAD

**Issue by bhupinder7** [mattfrear/Swashbuckle.Examples#2]
Great library to easily generate examples to display on swagger ui. However, I am having one issue with json request and response property’s case. I have declared models in c# as PascalCase and I want all properties to appear as PascalCase as well on the documentation page. However, on the documentation page, swagger ui automatically converts all property names to camelCase. I found a solution to change in swagger ui to define default contract resolver like below and then it shows property names to PascalCase. but this solution does not work with methods decorated with Swaggerexamples:

[SwaggerResponseExample(HttpStatusCode.OK,typeof(UserLoginResponseExample))]

Default contract resolver solution:

config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new DefaultContractResolver();

**Comment by AnthonyNeace** [comment]
There's a pull request in the netcore version of this project that should resolve this issue: https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/pull/1

**Comment by mattfrear** [comment]
I have ported @Klaven's PR into this project. If you pull the latest NuGet package (2.2), you should be able to get PascalCase by specifying a DefaultContractResolver:

`[SwaggerResponseExample(HttpStatusCode.OK, typeof(PersonResponseExample), typeof(DefaultContractResolver))]`
