### ISSUE TITLE
Example not added to swagger output

### ISSUE THREAD

**Issue by bobvandevijver** [mattfrear/Swashbuckle.Examples#20]
I'm working on an WebAPI in .NET 4.6.1, and I cannot get this examples package to work: the expected example output is not available in the generated swagger JSON file. So I'm probably missing something... Here are the relevant classes (simplified): 

**GeneralController.cs**
```c#
public class GeneralController : ApiController
{
    [HttpGet]
    [Route("cachecount")]
    [SwaggerResponse(HttpStatusCode.NotFound, Description = "The requested cache is not found.")]
    [SwaggerRequestExample(typeof(string), typeof(GetCacheCountExample))]
    public object GetCacheCount(string cacheName = null)
    {
        if (cacheName == null)
        {
            return _repository.GetCacheCounts();
        }

        return _repository.GetCacheCounts(cacheName);
    }

    [HttpGet]
    [Route("information")]
    [SwaggerRequestExample(typeof(GetGeneralInformationExampleModel), typeof(GetGeneralInformationExample),
        jsonConverter: typeof(StringEnumConverter))]
    public GeneralInformationViewModel GetGeneralInformation(DateTime? startFrom = null,
                                                             GeneralInfoType? type = null)
    {
        startFrom = startFrom?.ToUniversalTime() ?? DateTime.UtcNow.AddMonths(-1);

        return _repository.GetGeneralInformation(startFrom, type);
    }
}
```

**GetCacheCountExample.cs**
```c#
public class GetCacheCountExample:IExamplesProvider
{
    public object GetExamples()
    {
        return "test";
    }
}
```

**GetGeneralInformationExample.cs**
```c#
public class GetGeneralInformationExample : IExamplesProvider
{
    public object GetExamples()
    {
        return new GetGeneralInformationExampleModel
        {
            StartFrom = DateTime.UtcNow,
            Type = null
        };
    }
}

public class GetGeneralInformationExampleModel
{
    public DateTime? StartFrom { get; set; }

    public GeneralInfoType? Type { get; set; }
}
```

**Global.asax.cs```
```c#
GlobalConfiguration.Configuration
    .EnableSwagger(c =>
    {
        c.Schemes(new[] {"http"});
        c.DescribeAllEnumsAsStrings();
        c.OperationFilter<ExamplesOperationFilter>();
    })
    .EnableSwaggerUi();
```

I do spot the new model in the definitions part of the generated JSON. 

Using Swashbuckle.Core 5.6.0 and Swashbuckle.Examples 3.4.0.

**Comment by bobvandevijver** [comment]
So, I've found the problem: the examples are not supported when using query parameters. 

I've also checked the Swagger 2.0 specifications, and indeed, the schema part at parameters is only available when the parameters are in the request body. So basically, it appears that there is currently no method of specifying some example values for get request with Swagger. 

I will leave this issue open for know, I you agree with my conclusion you can close it.

**Comment by mattfrear** [comment]
Thanks for your investigation. I will leave the issue open for now and then add this to the list of known issues in the Readme so that hopefully someone else doesn't have the same problem.
