### ISSUE TITLE
Question: Global Settings

### ISSUE THREAD

**Issue by whoiskevinrich** [mattfrear/Swashbuckle.Examples#21]
Is there a way to set the contractResolver/jsonConverter globally? I tried looking around in the wiki docs and playing around with the params parameter in the SwaggerGen services setup `options.OperationFilter<ExamplesOperationFilter>();` to no avail. I'm probably missing something simple.

**Comment by whoiskevinrich** [comment]
Also, if it helps, I'm happy to update the docs when we get this figured out.

**Comment by mattfrear** [comment]
By default the examples will be output using the same serializerSettings the controller will use - how to set that I'm not sure, possibly `GlobalConfiguration.Configuration.Formatters.JsonFormatter.S‌​erializerSettings`?

Any settings you pass in via contractResolver or jsonConverter will overwrite those.
