### ISSUE TITLE
Different Error codes with same error type show same error message example

### ISSUE THREAD

**Issue by ghost** [mattfrear/Swashbuckle.Examples#22]
```
[SwaggerResponse((int)HttpStatusCode.BadRequest, Type = typeof(ErrorResponse))]
[SwaggerResponse((int)HttpStatusCode.NotAcceptable, Type = typeof(ErrorResponse))]
[SwaggerResponseExample((int)HttpStatusCode.NotAcceptable, typeof(ErrorResponseExamples.ErrorResponseInvalidOperationError), typeof(ErrorResponse))]
[SwaggerResponseExample((int)HttpStatusCode.BadRequest, typeof(ErrorResponseExamples.ErrorResponseIdNotValid), typeof(ErrorResponse))]
```
will show the same `ErrorResponseExamplse.ErrorResponseIdNotValid` 
for both BadRequest and NotAcceptable error types in swagger.

**Comment by ghost** [comment]
Seems to be a swagger issue? the Json generated has the different responses

![image](https://user-images.githubusercontent.com/29460335/31620853-ba724e8e-b26e-11e7-9e24-d3c5009065fe.png)
but the Swagger ui only shows the one
![image](https://user-images.githubusercontent.com/29460335/31620902-d294d39c-b26e-11e7-9250-e7b4a187905b.png)

**Comment by mattfrear** [comment]
Yep - it's listed in my Readme under Known issues. It's a swagger-ui bug.
