### ISSUE TITLE
SwaggerRequestExample always returns the same example

### ISSUE THREAD

**Issue by freeranger** [mattfrear/Swashbuckle.Examples#24]
Hi,

I have decorated different actions in different controllers with:
        [SwaggerRequestExample(typeof(JsonPatchDocument), typeof(PatchTypeOneExample))]

and
        [SwaggerRequestExample(typeof(JsonPatchDocument), typeof(PatchTypeTwoExample))]

ie, the input type is the same - JsonPatchDocument, but the example values are quite different, because they are patching different types of resources.

In my swagger docs though I am seeing the PatchTypeOneExample for both.
Is this a bug in the code, or is there some way to override the behaviour?

thanks

**Comment by freeranger** [comment]
Oops, wrong repo ;)

**Comment by jerrychoubear** [comment]
@freeranger hi there, so what did you do finally to solve this problem?

**Comment by mattfrear** [comment]
I don't really support this NuGet package anymore. 

The Swashbuckle.AspNetCore.Filters package supports JsonPatch - if you look at my answer on this issue it _might_ work for Swashbuckle.Examples.

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/44

**Comment by jerrychoubear** [comment]
Ok, I'll take a look at it, thanks for the quick reply.
