### ISSUE TITLE
Example not added to swagger output in case of string, byte and timespan 

### ISSUE THREAD

**Issue by jitsingh89** [mattfrear/Swashbuckle.Examples#25]
I not able to show example value of string, timespan, byte in swagger ui page. Error: 0x800a1391- Javascript runtime error: ‘jsyaml’ is undifned. To show example value i have created a class liker this
```
public class EmployeeExample: IExamplesProvider
{
    public object GetExamples()
    {
      return "Sample Value"; //  doing same this for timespan, byte , It's working fine for integer.
    }
```
Please let me how can i resolve this issue ?

**Comment by mattfrear** [comment]
I've never seen that error before. Can you show me what your controller looks like?

**Comment by jitsingh89** [comment]
**In StringResponseExample.cs**
```
using Swashbuckle.Examples;
namespace WebApi.Models.Examples
{
    public class StringResponseExample : IExamplesProvider
    {
        public object GetExamples()
        {
            return "Sample String 1";
        }
    }
}
```
**In PersonController.cs**
```
using Swashbuckle.Examples;
using Swashbuckle.Swagger.Annotations;
using System.Collections.Generic;
using System.Net;
using System.Web.Http;
using Newtonsoft.Json.Converters;
using WebApi.Models;
using WebApi.Models.Examples;
using System.Net.Http;
namespace WebApi.Controllers
{
    public class PersonController : ApiController
    {
        [HttpPost]
        [Route("api/Person/save")]
        [SwaggerResponseExample(HttpStatusCode.OK, typeof(StringRequestExample))]
        public HttpResponseMessage PostenericPerson(PersonRequest personRequest)
        {
            string result =  "Created";
            return Request.CreateResponse(HttpStatusCode.OK, result);
        }
    }
}
```
**This is the error i am getting **
![error](https://user-images.githubusercontent.com/9546697/33219944-3127b030-d16b-11e7-9885-111b13fbbbc5.png)

**Comment by mattfrear** [comment]
The jsyaml undefined thing looks like a known issue of swagger-ui which was fixed in 2016. https://github.com/swagger-api/swagger-ui/issues/2369

Aside from that, you're missing the `[SwaggerResponse]` attribute. I suggest you consult the Swashbuckle documentation to get started - this library is merely an extension of that one.

I am able to get the Swagger page loading for you with this:
```
[HttpPost]
[Route("api/Person/save")]
[SwaggerResponseExample(HttpStatusCode.OK, typeof(StringResponseExample))]
[SwaggerResponse(HttpStatusCode.OK, "Saves the person", typeof(string))]
public HttpResponseMessage PostenericPerson(PersonRequest personRequest)
{
    string result = "Created";
    return Request.CreateResponse(HttpStatusCode.OK, result);
}

public class StringResponseExample : IExamplesProvider
{
    public object GetExamples()
    {
        return "Sample String 1";
    }
}
```
The page loads, and the underlying Swagger document contains the correct example:
```
"/api/Person/save": {
	"post": {
		"tags": ["Values"],
		"operationId": "Values_PostenericPerson",
		"consumes": ["application/json", "text/json", "application/xml", "text/xml", "application/x-www-form-urlencoded"],
		"produces": ["application/json", "text/json", "application/xml", "text/xml"],
		"parameters": [{
				"name": "personRequest",
				"in": "body",
				"required": true,
				"schema": {
					"$ref": "#/definitions/PersonRequest"
				}
			}
		],
		"responses": {
			"200": {
				"description": "Saves the person",
				"schema": {
					"type": "string"
				},
				"examples": {
					"application/json": "Sample String 1"
				}
			}
		}
	}
```
However, unfortunately the Swagger-UI page doesn't display the example:
![swagger](https://user-images.githubusercontent.com/169179/33234574-30be4378-d221-11e7-8c8b-42bd404577c0.JPG)

This seems like another bug in swagger-ui; there's nothing I can do to fix it, but you may want to raise a bug against swagger-ui.

**Comment by mattfrear** [comment]
This works:
```
public class StringResponseExample : IExamplesProvider
{
    public object GetExamples()
    {
        return new { id = "Sample String 1" };
    }
}
```

**Comment by jitsingh89** [comment]
yes It's working but You are returning object with id  not a string. I have to return only string.
currently i am working in my project like this 
```
 public object GetExamples()
        {            
            List<string> lst = new List<string>();
            lst.Add("Sample String");
            return lstl
        }
```

This is also working fine. Output

![image](https://user-images.githubusercontent.com/9546697/36749759-b728f490-1c21-11e8-8ebb-f1df327327d3.png)

**Comment by TheBels** [comment]
Hello- I am a bit confused on this issue. As I understand the [Open API v2.0 spec](https://swagger.io/docs/specification/2-0/adding-examples/) for examples, the examples should include the mime-type. Per [ExamplesOperationFilter](https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/blob/9eb6b006d4ce5e65f829c5944a15ada8d6885b82/src/Swashbuckle.AspNetCore.Examples/Examples/ExamplesOperationFilter.cs#L133) the mime type is being given as `application/json`.

This works for JSON responses; however, what if you have a response mime type of `text/csv`? The Open API spec link above has an example with two mime types: JSON and text.

I tried adding `[Produces("text/csv")]` to my action, as well as the attribute `[SwaggerResponse(200, typeof(string))]`. However it doesn't seem to pick up that mime type for the example.

Specifically, this is the swagger YAML:
![example-json](https://user-images.githubusercontent.com/12475792/39547886-e80c5ade-4e26-11e8-80af-e887b82baffa.png)

This is how swagger-ui renders it:
![example-swagger-ui-json](https://user-images.githubusercontent.com/12475792/39547889-ea5e88b6-4e26-11e8-93a0-ece29a90af01.png)

And this is what I would expect/want based off the `Produces` attribute:
![example-text png](https://user-images.githubusercontent.com/12475792/39547891-ecc35230-4e26-11e8-9628-9b3081dcf645.png)

Is it possible to use a mime-type other than JSON?

**Comment by mattfrear** [comment]
Hi Bels,

Currently my library only supports json.

Thank you for your detailed report of what you have tried to do. However you've posted it in the wrong place - this issue is already closed.

Please raise a new issue and I will look at it when I get a chance. I am on holiday right now so it won't be for a while.

Matt

**Comment by TheBels** [comment]
Thanks for the reply, Matt, and understood.

I actually meant to log this against `Swashbuckle.AspNetCore.Examples`. I have entered an issue there: https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/issues/43.

**Comment by mattfrear** [comment]
@jitsingh89 I'm sure this is probably too late for you, but I have just tested this locally like this:
```csharp
        [HttpPost]
        [Route("api/Person/save")]
        [SwaggerResponse(200, "The person was saved", typeof(string))]
        [SwaggerResponseExample(200, typeof(StringResponseExample))]
        public IActionResult PostenericPerson(PersonRequest personRequest)
        {
            string result = "Created";
            return Ok(result);
        }

        public class StringResponseExample : IExamplesProvider
        {
            public object GetExamples()
            {
                return "Sample String 1";
            }
        }
```

and I think it's working
![image](https://user-images.githubusercontent.com/169179/42583171-60edc694-8528-11e8-9f2d-cec9f0581f8d.png)

This is using Swashbuckle.AspNetCore 3.0 and my new Swashbuckle.AspNetCore.Filters package (to be released soon)

**Comment by marctalary** [comment]
Looks cool, shelved the examples so will probably pick it up if you push it
anytime soon.

**Comment by jitsingh89** [comment]
Thanks @mattfrear

**Comment by diaznicolasandres1** [comment]
> @jitsingh89 I'm sure this is probably too late for you, but I have just tested this locally like this:
> 
> ```cs
>         [HttpPost]
>         [Route("api/Person/save")]
>         [SwaggerResponse(200, "The person was saved", typeof(string))]
>         [SwaggerResponseExample(200, typeof(StringResponseExample))]
>         public IActionResult PostenericPerson(PersonRequest personRequest)
>         {
>             string result = "Created";
>             return Ok(result);
>         }
> 
>         public class StringResponseExample : IExamplesProvider
>         {
>             public object GetExamples()
>             {
>                 return "Sample String 1";
>             }
>         }
> ```
> 
> and I think it's working
> ![image](https://user-images.githubusercontent.com/169179/42583171-60edc694-8528-11e8-9f2d-cec9f0581f8d.png)
> 
> This is using Swashbuckle.AspNetCore 3.0 and my new Swashbuckle.AspNetCore.Filters package (to be released soon)

This works, you saved me
