### ISSUE TITLE
Not able to show  HttpStatusCode.Created status code 

### ISSUE THREAD

**Issue by jitsingh89** [mattfrear/Swashbuckle.Examples#26]
I am not able to show  status code & Example value  if method return type is HttpStatusCode.Created on swagger ui.  It's working fine for return type  HttpStatusCode.Ok. 
This is my controller and Example value class

**In PersonController.cs**
```
 public class PersonController : ApiController
    {
        [HttpPost]
        [Route("api/Person/save")]
        [SwaggerResponseExample(HttpStatusCode.Created, typeof(PersonResponseExample))]
        public HttpResponseMessage PostenericPerson(PersonRequest personRequest)
        {
            var result = 1;// "Created";
            return Request.CreateResponse(HttpStatusCode.Created, result);
        }
    }
```
**In PersonResponseExample.cs**
```
 internal class PersonResponseExample : IExamplesProvider
    {
        public object GetExamples()
        {
            return new PersonResponse
            {
                Id = 123,
                Title = Title.Dr,
                FirstName = "John",
                LastName = "Doe",
                Age = 27,
                Income = null
            };
        }
    }
```

This is the output i want to get i have mark in red.
![ui](https://user-images.githubusercontent.com/9546697/33220310-2afdd6a6-d16d-11e7-86ec-fcdbf1c3b9f2.PNG)

Please let me know am i missing anything.

**Comment by mattfrear** [comment]
You need to define a ` [SwaggerResponse(HttpStatusCode.Created,...]` attribute first. Then the `[SwaggerResponseExample]`

**Comment by jitsingh89** [comment]
Hi i have changed attribute but it's working fine with HttpStatusCode.Ok. Not working with HttpStatusCode.Created.

**I have created two methods,please see below method**

```
  [HttpPost]
        [Route("api/Person/saveok")]
        [SwaggerResponse(HttpStatusCode.OK, "Ok", typeof(PersonResponseExample))]
        [SwaggerResponseExample(HttpStatusCode.OK, typeof(PersonResponseExample))]
        public HttpResponseMessage SavePersonOk(PersonRequest personRequest)
        {
            var result = new PersonResponse
            {
                Id = 123,
                Title = Title.Dr,
                FirstName = "John",
                LastName = "Doe",
                Age = 27,
                Income = null
            };
            return Request.CreateResponse(HttpStatusCode.Created, result);
        }

        
        [HttpPost]
        [Route("api/Person/savecreted")]
        [SwaggerResponse(HttpStatusCode.Created, "created", typeof(PersonResponseExample))]
        [SwaggerResponseExample(HttpStatusCode.Created, typeof(PersonResponseExample))]
        public HttpResponseMessage SavePersonCreated(PersonRequest personRequest)
        {
            var result = new PersonResponse
            {
                Id = 123,
                Title = Title.Dr,
                FirstName = "John",
                LastName = "Doe",
                Age = 27,
                Income = null
            };
            return Request.CreateResponse(HttpStatusCode.Created, result);
        }
```

**This is result on ui**

**with ok**
![1](https://user-images.githubusercontent.com/9546697/33241194-fe7f8026-d2e7-11e7-9105-bf99f758241e.png)

**with created**
![2](https://user-images.githubusercontent.com/9546697/33241198-0730821a-d2e8-11e7-8c55-879f0adbd995.PNG)

**Comment by mattfrear** [comment]
`[SwaggerResponse(HttpStatusCode.OK, "Ok", typeof(PersonResponseExample))]` should be `[SwaggerResponse(HttpStatusCode.OK, "Ok", typeof(PersonResponse))]`. Try that

**Comment by jitsingh89** [comment]
It's working fine if statuse code is 
  [SwaggerResponse(HttpStatusCode.Ok, "Ok", typeof(PersonResponse))]
But not working with 
  [SwaggerResponse(HttpStatusCode.Created, "Created", typeof(PersonResponse))]

Showing blank example value and status code is 200 like this

Response Class (Status 200)
OK


**this is output**

![12](https://user-images.githubusercontent.com/9546697/33241617-17a81b52-d2ee-11e7-9dbe-b1f448295ba0.PNG)

**Comment by jitsingh89** [comment]
This is my project
https://github.com/jitsingh89/Swashbuckle.Examples

Could you please reopen this issue if this is issue?

**Comment by mattfrear** [comment]
I had a look at your example. Your syntax is incorrect, it should be like this:
```
[HttpPost]
[Route("api/Person/savecreted")]
       
[SwaggerResponse(HttpStatusCode.Created, "Created", typeof(PersonResponse))]
[SwaggerResponseExample(HttpStatusCode.Created, typeof(PersonResponseExample))]
public HttpResponseMessage SavePersonCreated(PersonRequest personRequest)
{
```

With that syntax, it IS working, as the Swagger document does contain the correct example for the 201 response:
```
"/api/Person/savecreted": {
	"post": {
		"tags": ["Person"],
		"operationId": "Person_SavePersonCreated",
		"consumes": ["application/json", "text/json", "application/xml", "text/xml", "application/x-www-form-urlencoded"],
		"produces": ["application/json", "text/json", "application/xml", "text/xml"],
		"parameters": [{
				"name": "personRequest",
				"in": "body",
				"required": true,
				"schema": {
					"$ref": "#/definitions/PersonRequest"
				}
			}
		],
		"responses": {
			"200": {
				"description": "OK",
				"schema": {
					"type": "object"
				}
			},
			"201": {
				"description": "Created",
				"schema": {
					"$ref": "#/definitions/PersonResponse"
				},
				"examples": {
					"application/json": {
						"id": 123,
						"title": 1,
						"firstName": "John",
						"lastName": "Doe",
						"age": 27
					}
				}
			}
		}
	}
},
```

However, the example is NOT showing up in swagger-ui. I forgot about that, but this is a Known issue and already documented in my project's readme section under [Known Issues](https://github.com/mattfrear/Swashbuckle.Examples#known-issues).

> Although you can add a response examples for each HTTP status code (200, 400, 404 etc), and they will appear in the swagger.json, they will not display correctly. This is due to an bug in swagger-ui. Issue 9

Just so you know, the 201 example should be here:
![swagger 2](https://user-images.githubusercontent.com/169179/33242951-77f95af8-d2d4-11e7-9114-e24d7ecf9eac.jpg)

**Comment by jitsingh89** [comment]
Thanks, But why 201 response code doesn't displayed on top with example value. it's displayed on top with status code 200.in my all API response code I have to display response type in top where it's showing blank and status code is 200 instead of 201.
Is it known issue which you have mentioned in documents.
Or we can displayed 201 on top of response call.

**Comment by mattfrear** [comment]
I just did a quick google, and this will get rid of the unwanted 200 response, and now the example is displayed fine for the 201:
```
[HttpPost]
[Route("api/Person")]
[SwaggerResponseRemoveDefaults]
[SwaggerResponse(HttpStatusCode.Created, "Created", typeof(PersonResponse))]
[SwaggerResponseExample(HttpStatusCode.Created, typeof(PersonResponseExample))]
public HttpResponseMessage Created(PersonRequest personRequest)
```

**Comment by jitsingh89** [comment]
Thanks It's working fine now, but It's not working with integer
[HttpPost]
[Route("api/Person")]
[SwaggerResponseRemoveDefaults]
[SwaggerResponse(HttpStatusCode.Created, "Created", typeof(int))]
[SwaggerResponseExample(HttpStatusCode.Created, typeof(NumericResponseExample))]
public HttpResponseMessage Created(PersonRequest personRequest)
{
int result=10;
  return Request.CreateResponse(HttpStatusCode.Created, result);
}

public class NumericResponseExample: IExampleProvider
{
Public object GetExamples(){
return 0;
}
}

in that case it;s displaying 200 without example value.

**Comment by mattfrear** [comment]
What's in the swagger.json? Is the example in there?

**Comment by jitsingh89** [comment]
**Controller Method**
```
 [HttpPost]
        [Route("api/Person/Numeric")]
        [SwaggerResponseRemoveDefaults]
        [SwaggerResponse(HttpStatusCode.Created, "Created", typeof(int))]
        [SwaggerResponseExample(HttpStatusCode.Created, typeof(NumericResponseExample))]
        public HttpResponseMessage SaveNumericData(List<int> lst)
        {
            int result = 10;
            return Request.CreateResponse(HttpStatusCode.Created, result);
        }

**NumericResponseExample class**
 public class NumericResponseExample : IExamplesProvider
    {
        public object GetExamples()
        {
            return 1;
        }
    }

**JSON **

> {
	"swagger": "2.0",
	"info": {
		"version": "v1",
		"title": "WebApi"
	},
	"host": "localhost:60613",
	"schemes": ["http"],
	"paths": {
		"/api/Person/Numeric": {
			"post": {
				"tags": ["Person"],
				"operationId": "Person_SaveNumericData",
				"consumes": ["application/json", "text/json", "application/xml", "text/xml", "application/x-www-form-urlencoded"],
				"produces": ["application/json", "text/json", "application/xml", "text/xml"],
				"parameters": [{
					"name": "lst",
					"in": "body",
					"required": true,
					"schema": {
						"type": "array",
						"items": {
							"format": "int32",
							"type": "integer"
						}
					}
				}],
				"responses": {
					"201": {
						"description": "Created",
						"schema": {
							"format": "int32",
							"type": "integer"
						},
						"examples": {
							"application/json": 1
						}
					}
				}
			}
		}
	},
	"definitions": {}
}
```

**On UI**

![1212121](https://user-images.githubusercontent.com/9546697/33268620-e1ebf450-d3a3-11e7-8884-4b55e35c149b.PNG)

**Comment by mattfrear** [comment]
First you complain that integers don't work. Now you're passing a `List<int>`. The example you've posted above is working, as you can see in the swagger.json:
```
                                                "examples": {
							"application/json": 1
						}
```
If it's not appearing in the UI then that is a swagger-ui issue, which is a separate package. Swashbuckle and my library are only concerned with the output of the swagger.json, not the UI.

FWIW I released a version of Swashbuckle.Examples that supports `List<T>` only yesterday, so you might want to try upgrading to that version.

But honestly, I don't have time to help you any more. I've spent a couple of hours helping you already, more than I've had to help anyone else. This issue is closed and I will not be replying to it any more.

**Comment by jitsingh89** [comment]
you have helped me a lot. Thank you very much
