### ISSUE TITLE
Doesn't generate example data for XML Accepts type

### ISSUE THREAD

**Issue by danpetitt** [mattfrear/Swashbuckle.Examples#3]
Is this known behaviour, as my swagger file doesnt get an XML example type, just JSON and as such when you select XML from the Swagger UI you just get an error.

**Comment by mattfrear** [comment]
Hi @coderangerdan,

Sorry for the delay in replying. How do you select XML in the Swagger UI? I don't see that anywhere.

**Comment by mattfrear** [comment]
Closing this as I don't know how to reproduce

**Comment by mattfrear** [comment]
FWIW this is now fixed in my  Swashbuckle.AspNetCore.Filters package
