### ISSUE TITLE
Swagger page Not loading request value of all version of apis if order of parameters and number of parameter  are same.

### ISSUE THREAD

**Issue by jitsingh89** [mattfrear/Swashbuckle.Examples#30]
There are 3 different version of apis, which is below.
```<HttpPost>
<VersionedRoute("", "2.0")>
Public Function PostValue(<FromBody()> ByVal userModel As UserInfo) As HttpResponseMessage

<VersionedRoute("", "2.2")>
Public Function PostValue_V2(<FromBody()> ByVal userModel As UserInfo) As HttpResponseMessage

<VersionedRoute("", "2.3")>
Public Function PostValue_v3(<FromBody()> ByVal userModel As UserInfo) As HttpResponseMessage**
```
These apis are not displaying  **request example value** on swagger ui page. only first version (2.0) is displaying on ui.  But we want to show all version of request example value on  swagger ui page.

I am getting this error if order of parameter and number of parameter are same. if order of parameters and number of parameters are changed then i am not getting this issue. below is action.
```<VersionedRoute("", "2.3")>
Public Function PostValue_v3(name as String, <FromBody()> ByVal userModel As UserInfo) As HttpResponseMessage
```

**Comment by mattfrear** [comment]
You need to declare the `[SwaggerRequestExample]` attribute. I have no idea what the VB.NET syntax for this is.

**Comment by jitsingh89** [comment]
but not supporting in that case too.  `<SwaggerRequestExample(GetType(UserInfo), GetType(UserInfoRequestExample))>`  I have tried this

**Comment by jitsingh89** [comment]
Problem is that it's displaying first version of apis like (2.0)

**Comment by mattfrear** [comment]
I have never tried using my library with `[VersionedRoute]`. I will investigate this when I get some time.

Please post more detail of your controller methods, and your `UserModel` and `UserModelRequestMessage`.

Please ensure you use github's formatting when posting source code (the Insert Code button).

**Comment by jitsingh89** [comment]
`  public class UserModel
    {
        [Required()]
        [StringLength(255)]
        public string UserName { get; set; }
        [StringLength(255)]      
        public List<GroupModel> Groups { get; set; }
        public System.DateTime? LastPasswordChange{ get; set; }
        public System.DateTime? LastLogon { get; set; }
        public List<KeyValuePair<string, DateTime?>> LastAdministrativeActivity { get; set; }
        public List<KeyValuePair<string, DateTime?>> LastProductionActivity { get; set; }
        public UserModel()
        { }
        public UserModel(DCG.UserManagement.SecurityUserModel securityUserModel)
        {
            LastLogon = securityUserModel.LastLogon;
            LastPasswordChange = securityUserModel.LastPasswordChange;
            LastAdministrativeActivity = securityUserModel.LastAdministrativeActivity;
            LastProductionActivity = securityUserModel.LastProductionActivity;        
            Groups = new List<GroupModel>();
        }
    }
    public class GroupModel
    {
        [Required]
        public int? efPermClientInterface
        {
            get; set;
        }
        [Required]
        public int? efPermClientApp
        {
            get; set;
        }
        [Required]
        public int? efPermAdminClient
        {
            get; set;
        }
        [Required]
        public int? efPermMgmt
        {
            get; set;
        }
        public int? groupId
        {
            get; set;
        }
        [Required]
        [StringLength(255)]
        public string groupName
        {
            get; set;
        }
        public string groupDescription
        {
            get; set;
        }
        public List<int> UserIds
        {
            get; set;
        }
        public GroupModel()
        {
            this.UserIds = new List<int>();
        }
    }
 public class UserModelRequestMessage : IExamplesProvider
    {
        public object GetExamples()
        {
            UserModel pc = new UserModel()
            {
                LastLogon = DateTime.Now,               
                LastPasswordChange = DateTime.Now,           
                UserName = "Sample string 5",
                Groups = new List<GroupModel>(),
                LastProductionActivity = new List<KeyValuePair<string, DateTime?>>(),
                LastAdministrativeActivity = new List<KeyValuePair<string, DateTime?>>()
            };
            return pc;
        }
    }
`

**Comment by jitsingh89** [comment]
` public class UserModel
    {
        [Required()]
        [StringLength(255)]
        public string UserName { get; set; }
        [StringLength(255)]      
        public List<GroupModel> Groups { get; set; }
        public System.DateTime? LastPasswordChange{ get; set; }
        public System.DateTime? LastLogon { get; set; }
        public List<KeyValuePair<string, DateTime?>> LastAdministrativeActivity { get; set; }
        public List<KeyValuePair<string, DateTime?>> LastProductionActivity { get; set; }
        public UserModel()
        { }
        public UserModel(DCG.UserManagement.SecurityUserModel securityUserModel)
        {
            LastLogon = securityUserModel.LastLogon;
            LastPasswordChange = securityUserModel.LastPasswordChange;
            LastAdministrativeActivity = securityUserModel.LastAdministrativeActivity;
            LastProductionActivity = securityUserModel.LastProductionActivity;        
            Groups = new List<GroupModel>();
        }
    }
    public class GroupModel
    {
        [Required]
        public int? efPermClientInterface
        {
            get; set;
        }
        [Required]
        public int? efPermClientApp
        {
            get; set;
        }
        [Required]
        public int? efPermAdminClient
        {
            get; set;
        }
        [Required]
        public int? efPermMgmt
        {
            get; set;
        }
        public int? groupId
        {
            get; set;
        }
        [Required]
        [StringLength(255)]
        public string groupName
        {
            get; set;
        }
        public string groupDescription
        {
            get; set;
        }
        public List<int> UserIds
        {
            get; set;
        }
        public GroupModel()
        {
            this.UserIds = new List<int>();
        }
    }
 public class UserModelRequestMessage : IExamplesProvider
    {
        public object GetExamples()
        {
            UserModel pc = new UserModel()
            {
                LastLogon = DateTime.Now,               
                LastPasswordChange = DateTime.Now,           
                UserName = "Sample string 5",
                Groups = new List<GroupModel>(),
                LastProductionActivity = new List<KeyValuePair<string, DateTime?>>(),
                LastAdministrativeActivity = new List<KeyValuePair<string, DateTime?>>()
            };
            return pc;
        }
    }`

**Comment by jitsingh89** [comment]
```
using Swashbuckle.Examples;
using System;
using System.Collections.Generic;
namespace SwaggerWebAPI.Models
{
    //UserInfo
    public class UserInfo
    {
        public string UserName
        {
            get; set;
        }
        public string Password
        {
            get; set;
        }
        public List<GroupInfo> Groups
        {
            get; set;
        }
        public System.DateTime? LastLogon
        {
            get; set;
        }
        public List<string> Activity
        {
            get; set;
        }
        public UserInfo()
        {
        }
    }
    //Group Info
    public class GroupInfo
    {
        public int ID
        {
            get; set;
        }
        public string Name
        {
            get; set;
        }
        public string Description
        {
            get; set;
        }
        public GroupInfo()
        {
        }
    }
    // Swagger resuest example
    class UserInfoRequestExample : IExamplesProvider
    {
        public object GetExamples()
        {
            return new UserInfo()
            {
                UserName = "jitsingh89",
                LastLogon = DateTime.Now,
                Password = "temp@123",
                Groups = new List<GroupInfo>(),
                Activity = new List<string>(),
            };
        }
    }
}
```

**Comment by jitsingh89** [comment]
`  public class UserModel
    {
        [Required()]
        [StringLength(255)]
        public string UserName { get; set; }
        [StringLength(255)]      
        public List<GroupModel> Groups { get; set; }
        public System.DateTime? LastPasswordChange{ get; set; }
        public System.DateTime? LastLogon { get; set; }
        public List<KeyValuePair<string, DateTime?>> LastAdministrativeActivity { get; set; }
        public List<KeyValuePair<string, DateTime?>> LastProductionActivity { get; set; }
        public UserModel()
        { }
        public UserModel(DCG.UserManagement.SecurityUserModel securityUserModel)
        {
            LastLogon = securityUserModel.LastLogon;
            LastPasswordChange = securityUserModel.LastPasswordChange;
            LastAdministrativeActivity = securityUserModel.LastAdministrativeActivity;
            LastProductionActivity = securityUserModel.LastProductionActivity;        
            Groups = new List<GroupModel>();
        }
    }
    public class GroupModel
    {
        [Required]
        public int? efPermClientInterface
        {
            get; set;
        }
        [Required]
        public int? efPermClientApp
        {
            get; set;
        }
        [Required]
        public int? efPermAdminClient
        {
            get; set;
        }
        [Required]
        public int? efPermMgmt
        {
            get; set;
        }
        public int? groupId
        {
            get; set;
        }
        [Required]
        [StringLength(255)]
        public string groupName
        {
            get; set;
        }
        public string groupDescription
        {
            get; set;
        }
        public List<int> UserIds
        {
            get; set;
        }
        public GroupModel()
        {
            this.UserIds = new List<int>();
        }
    }
 public class UserModelRequestMessage : IExamplesProvider
    {
        public object GetExamples()
        {
            UserModel pc = new UserModel()
            {
                LastLogon = DateTime.Now,               
                LastPasswordChange = DateTime.Now,           
                UserName = "Sample string 5",
                Groups = new List<GroupModel>(),
                LastProductionActivity = new List<KeyValuePair<string, DateTime?>>(),
                LastAdministrativeActivity = new List<KeyValuePair<string, DateTime?>>()
            };
            return pc;
        }
    }
`

**Comment by mattfrear** [comment]
Post your controller actions and attributes too

**Comment by jitsingh89** [comment]
`  <HttpPost>
        <SwaggerRequestExample(GetType(UserModel), GetType(UserModelRequestMessage))>
        <VersionedRoute("", "6.5")>
        Public Function PostValue_V2(<FromBody()> ByVal userModel As UserModel) As HttpResponseMessage
            Try
                Dim value As Integer = 10
                Return Request.CreateResponse(HttpStatusCode.OK, value)
            Catch ex As Exception
                Throw WebApiExceptionHelper.ToHttpResponseException(ex)
            End Try
        End Function`

**Comment by jitsingh89** [comment]
Other two controller are same only version is changed. like <VersionedRoute("", "6.3")>, <VersionedRoute("", "6.4")>

**Comment by jitsingh89** [comment]
```<HttpPost>
        <SwaggerRequestExample(GetType(UserInfo), GetType(UserInfoRequestExample))>
        <VersionedRoute("", "2.3")>
        Public Function PostValue_V2(<FromBody()> ByVal userModel As UserInfo) As HttpResponseMessage
            Try               
                Return Request.CreateResponse(HttpStatusCode.OK)
            Catch ex As Exception
                Throw ex
            End Try
        End Function```

**Comment by jitsingh89** [comment]
Hi I have updated my comment and classes, i have also send the code. you can suggest me in C#  if you have problem in vb. i will change into c#. waiting for your response.

**Comment by mattfrear** [comment]
What is the `[VersionedRoute]` attribute you are using? That's not a standard web api attribute. Can you see your 3 endpoints in Swagger?  Is `[SwaggerRequestExample]` what is causing problems?

As I said, I don't know what `[VersionedRoute]` is, but it works fine for me if I use the standard `[Route]` attribute:
```
[HttpPost]
[Route("api/jitendra/v1")]
[SwaggerRequestExample(typeof(UserInfo), typeof(UserInfoRequestExample))]
public IHttpActionResult PostValue(UserInfo userModel)
{
    return Ok();
}

[HttpPost]
[Route("api/jitendra/v2")]
[SwaggerRequestExample(typeof(UserInfo), typeof(UserInfoRequestExample))]
public IHttpActionResult PostValue_V2(UserInfo userModel)
{
    return Ok();
}

[HttpPost]
[Route("api/jitendra/v3")]
[SwaggerRequestExample(typeof(UserInfo), typeof(UserInfoRequestExample))]
public IHttpActionResult PostValue_V3(UserInfo userModel)
{
    return Ok();
}
```
![screenshot-2018-1-23 swagger ui](https://user-images.githubusercontent.com/169179/35284323-66f3aa00-0052-11e8-9872-0f07340a3f41.png)

FYI (and this is beyond the scope of my library), the correct way to specify multiple API versions with Swashbuckle is in your .EnableSwagger() method in `SwaggerConfig.cs`:
```
                        // If your API has multiple versions, use "MultipleApiVersions" instead of "SingleApiVersion".
                        // In this case, you must provide a lambda that tells Swashbuckle which actions should be
                        // included in the docs for a given API version. Like "SingleApiVersion", each call to "Version"
                        // returns an "Info" builder so you can provide additional metadata per API version.
                        //
                        //c.MultipleApiVersions(
                        //    (apiDesc, targetApiVersion) => ResolveVersionSupportByRouteConstraint(apiDesc, targetApiVersion),
                        //    (vc) =>
                        //    {
                        //        vc.Version("v2", "Swashbuckle Dummy API V2");
                        //        vc.Version("v1", "Swashbuckle Dummy API V1");
                        //    });
```

**Comment by jitsingh89** [comment]
Hi you have change the url. we don't need to change url.  URLwill be same like "api/jitendra". Version will be  changed which i have already share in my action. we are able to load controller but not able to load request example data for all version. all time it's showing first version data.

**Comment by mattfrear** [comment]
Since you're using a non-standard `[VersionedRoute]` attribute I'm not going to spend any more time investigating this.
