### ISSUE TITLE
Additional Response Message Examples Not Working

### ISSUE THREAD

**Issue by IAmShipy** [mattfrear/Swashbuckle.Examples#32]
The main 200 response works as expected, but when you add additional response examples the default automatic example is only shown, not the one specified with, for example: -

    [SwaggerResponse(HttpStatusCode.BadRequest, Type = typeof(BadRequestResponse))]
    [SwaggerResponseExample(HttpStatusCode.BadRequest, typeof(BadRequestResponseExample))]

    [SwaggerResponse(HttpStatusCode.InternalServerError, Type = typeof(ErrorResponseMessage))]
    [SwaggerResponseExample(HttpStatusCode.InternalServerError, typeof(InternalServerErrorResponseExample))]

I've downloaded the example project and the results are basically the same.  The default example is only included if [SwaggerResponse] has a type included, [SwaggerResponseExample] seems to be ignored.

**Comment by jitsingh89** [comment]
can you share your controller and Response Example classes.
Add this to your method.
[SwaggerResponseRemoveDefaults]

For help you can check this issue.

[https://github.com/mattfrear/Swashbuckle.Examples/issues/26](url)

**Comment by IAmShipy** [comment]
Hi Jitendra,

Thank you for getting back to me.  I tried using the [SwaggerResponseRemoveDefaults] without success.  

This issue also exists within the example project (Swashbuckle.Examples.csproj) as can be seen here, the 404 and 500 examples are not included although they are defined within the code: -

![Example](https://photos-6.dropbox.com/t/2/AABOgecSvUXkaIQpXkzSSICxxDz6YG_MJKsLq18J7_zegQ/12/4951943/png/32x32/3/1520262000/0/2/2018-03-05%2010_48_37-Photos.png/EOTM2gMY6dUKIAcoBw/x4ZMU-fMJqKS9fID6PXPt3JCf84Zg0L4FbePxzjGWJM?dl=0&preserve_transparency=1&size=1600x1200&size_mode=3)

**Comment by IAmShipy** [comment]
Ok, just [seen this](https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/issues/9), so it's a known issue :-(
