### ISSUE TITLE
SwaggerRequestExample should not have to match the type in method

### ISSUE THREAD

**Issue by nycdanielp** [mattfrear/Swashbuckle.Examples#34]
I have a method that takes a generic JObject, so it's not really defined anywhere what the contents should look like and thus it's hard to get an example. However, I later map that JObject to a specific type. So I would like to set this type in the SwaggerRequestExample and have that appear in the example because that will mirror what my request body should look like. I am able to to this with Swashbuckle.Examples. However, a fatal error occurs in Swashbuckle.AspNetCore.Examples when I attempt the same thing.

**Comment by mattfrear** [comment]
Interesting. Sorry, but can you log this issue over in  Swashbuckle.AspNetCore.Examples. Can you also post how you're using the SwaggerRequestExample attribute and your IExamplesProvider.
