### ISSUE TITLE
Not able to show Request/Response example in XML format (application/xml)

### ISSUE THREAD

**Issue by jitsingh89** [mattfrear/Swashbuckle.Examples#35]
![image](https://user-images.githubusercontent.com/9546697/41907994-24932e74-7960-11e8-8148-b39ec66d5e94.png)

I want to display response and request value in  application/xml or xml/text

**Comment by mattfrear** [comment]
Yep, this is a known issue. I'll think about fixing it.

**Comment by jitsingh89** [comment]
Thanks,


I am not able to display the JSON format for methods  parameter. I have follw the below lines.

1)update in config file

 c.OperationFilter<ExamplesOperationFilter>();

2) decorated on methods
[SwaggerRequestExample(typeof(DeliveryOptionsSearchModel), typeof(DeliveryOptionsSearchModelExample))]

**Comment by mattfrear** [comment]
@jitsingh89 your problem is unrelated to this issue, can you open a new issue please. 

I have extensive documentation and examples listed in the readme, please ensure you have read that correctly. 

If you are still having problems, post what you are trying to do, what you are expecting to see, and what you actually see in a new github issue.

**Comment by dbednar13** [comment]
This is something I'd like as well if the votes matter.  In our use cases we don't always need to show all fields, just the more common ones (the rest are documented elsewhere) and the mismatch between the JSON examples and the XML is confusing to some of our users.

**Comment by mattfrear** [comment]
I've never actually written an API that returned XML in ASP.NET Web Api (only ever used JSON), so right now I don't know a) how to do that and b) what support Swashbuckle provides out of the box for XML. If someone can answer those two questions then I could look at supporting XML, when I eventually have some spare time one day.

**Comment by mattfrear** [comment]
I added XML examples to my .NET Core version of this project, back in version 5.0.0.

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters

I'm not going to add that support to this project, so I'm closing this issue.
