### ISSUE TITLE
Descriptions not resolved if custom serialization settings

### ISSUE THREAD

**Issue by joostbroekhuizen** [mattfrear/Swashbuckle.Examples#37]
I have a solution where I have a CamelCasePropertyNamesContractResolver registered on my api. 
The UpdatePropertyDescription in the DescriptionOperationFilter cannot handle that as it takes my PascalCased property names to compare the property names with. 
Would be helpful if the comparison would be case insensitive.

**Comment by mattfrear** [comment]
Can you post code samples to help me reproduce this?

**Comment by joostbroekhuizen** [comment]
yes of course, all it takes is adding following line in WebApiConfig.cs:

            config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver();

**Comment by mattfrear** [comment]
OK, I'll have a look at this later today

**Comment by mattfrear** [comment]
Released in https://www.nuget.org/packages/Swashbuckle.Examples/3.9.3

**Comment by joostbroekhuizen** [comment]
Thanks for the quick fix, happy user now.
