### ISSUE TITLE
Swashbuckle Example adding "application/json" to display

### ISSUE THREAD

**Issue by ericwallin** [mattfrear/Swashbuckle.Examples#41]
SwaggerResponseExample is adding an "application/json": { }  wrapper around the example in my swagger when using v5.6.0 of Swashbuckle and Swashbuckle.Core nuget packages with Swashbuckle.Examples v3.10.0.  Rolling back the versions to v5.5.3 of Swashbuckle & Swashbuckle.Core, along with rolling back to Swashbuckle.Examples v3.9.4 appears to correct that issue.

I'm experiencing the same issue that has been reported by Inga on Oct. 7, 2017 on this page:

https://mattfrear.com/2015/04/21/generating-swagger-example-responses-with-swashbuckle/

----

> Inga
> October 6, 2017 at 10:42 am
> Hi,
> I’m glad I’ve found this post and tried this lib immediately!
> But I found one unexpected behavior. Json is generated the same as expected, but UI response example shows property ‘application/json’. It shows example:
> {
> “application/json”: {
> “id”: 1
> }
> }
> but I would expect to see:
> {
> “id”: 1
> }
> 
>
>Maybe you know, where the issue is?
>
----
>
>mattfrear
>October 6, 2017 at 3:11 pm
>
>Yes, that started happening with more recent versions of Swashbuckle.
>The Swagger that I am outputting is valid Swagger, so I’m not sure why Swagger-UI is displaying it >incorrectly. I have found a workaround but I haven’t had time to implement it yet.>

**Comment by mattfrear** [comment]
This is a known issue, as described here
https://github.com/mattfrear/Swashbuckle.Examples#known-issues

See also #8.

**Comment by pjc2007** [comment]
I don't suppose there is any "hacky" work around at all? (until I get get to .net core/5)?

**Comment by mattfrear** [comment]
> 
> 
> I don't suppose there is any "hacky" work around at all? (until I get get to .net core/5)?

Well... if you don't care that the swagger.json is invalid, then you can fork the code yourself and make the changes.
Or, you could roll back to the previous versions as mentioned in this very issue by ericwallin.
