### ISSUE TITLE
SwaggerResponseExample hiding null properties in Swagger UI

### ISSUE THREAD

**Issue by jlnpinheiro** [mattfrear/Swashbuckle.Examples#42]
When my example type has a null property the Swagger UI ("Example value") is hiding this property. How can I show it?

**Comment by mattfrear** [comment]
Hi, that is by design, as nulls aren't allowed in request examples according to the Swagger 2.0 spec. Is your null in a request example or a response example? Also, are you using the Swashbuckle.Examples NuGet package or the ASP.NET Core version?

**Comment by mattfrear** [comment]
I have changed it so that nulls are now shown in response examples. Released in https://www.nuget.org/packages/Swashbuckle.Examples/3.11.0

**Comment by jlnpinheiro** [comment]
Thanks for your help, my friend!
