### ISSUE TITLE
Authentication not supported in Asp .net MVC

### ISSUE THREAD

**Issue by Rajatnigam9** [mattfrear/Swashbuckle.Examples#46]
The Basic HTTP Authentication header is not supported in Asp .Net MVC web API project. I have tried all the fixes in the swagger config file but neither I get the pop-up for entering authentication key nor I get the input field for the same.

**Comment by mattfrear** [comment]
What are you trying to do? I think your issue does not belong in this repository. Please explain what you have tried and how it relates to this repository.

**Comment by mattfrear** [comment]
This is not an issue here for this project.

Please see the documentation over at https://github.com/domaindrivendev/Swashbuckle.WebApi#describing-securityauthorization-schemes
