### ISSUE TITLE
Examples not working if Swagger is used with swagger 2.0 instead of openapi 3.0.1

### ISSUE THREAD

**Issue by DanikRaikhlin** [mattfrear/Swashbuckle.Examples#49]
Whenever UseSwagger(x => x.SerializeAsV2 = true) the examples are not generated in the swagger.json. The cause is that now the examples are generated on Operation.RequestBody and before the example was generated on the definition of the object itself.

There are tools like AutoRest that still require swagger 2.0 version of swagger.json so as long SerializeAsV2 exists it would be nice to have working examples in that scenario.

**Comment by mattfrear** [comment]
Hi

I'm closing this as it is a duplicate of https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/115
