### ISSUE TITLE
ExamplesOperationFilter Serializes Null

### ISSUE THREAD

**Issue by matt-snyder-clear** [mattfrear/Swashbuckle.Examples#5]
One of the overloads does not specify that it should ignore null values, while another overload does:

line 69:
var serializerSettings = new JsonSerializerSettings { ContractResolver = attr.ContractResolver };

**Comment by mattfrear** [comment]
I've ported your PR from Swashbuckle.AspNetCore.Examples to here, thanks.

Fixed in commit bbd1fe464ee2019850ed71e7cb21c947f83d8cad
