### ISSUE TITLE
Zero valued enums are not included in examples

### ISSUE THREAD

**Issue by mihalios** [mattfrear/Swashbuckle.Examples#51]
Assume the following:

```
Item
{
   public string Name {get; set;}
   public ItemType Type {get; set;}
}

enum ItemType
{
     Product = 0,
     Service = 1
}
```

And the following example:
```
Item GetExamples()
{
   return new Item { 
              Name = "Apple"; 
              Type = ItemType.Product;
              }
}
```

When referencing Swashbuckle.AspNetCore.Filters 4.5.5 this used to display fine in Swagger. Upgrading to 5.0.0-rc8 the example was displayed fine except for the Type, that's no longer there. Changing it to ItemType.Service it worked fine.

This made me think that 0-values are not considered valid in the example construction. Is this a known issue, or possibly by new design?

**Comment by mattfrear** [comment]
Hmm, I don't know. I don't think there's anything in my code that would hide it. Maybe there's something in the OpenApi spec? Maybe it's being treated as null and being hidden? What can you see in in the swagger.json?

**Comment by mihalios** [comment]
@mattfrear Thanks. I also couldn't see anything in your code that would hide it. In Swagger.json it's missing too. A quick google search didn't reveal anything, I'm going to park this assuming 0-valued enums are hidden.
