### ISSUE TITLE
[SwaggerRequestExample] Non-nullable types

### ISSUE THREAD

**Issue by vschuboth** [mattfrear/Swashbuckle.Examples#54]
Hello,

we want to create an example in a minimalist way for our api users with Swashbuckle.Examples.
In our use case we do not always need to send all fields, just the required ones.

For instance, if I want to store an article I need the article number and a quantity. 
I do not need to send the information of its weight (Double) or expiration date (DateTime).

![example_code](https://user-images.githubusercontent.com/34538107/96451269-9cd9cf80-1217-11eb-9464-bb52025dc224.png)

I left out this information in my request example. Nevertheless Swagger shows all non-nullable fields (bool, int, … ) and their default values.

![example_swagger](https://user-images.githubusercontent.com/34538107/96451267-9c413900-1217-11eb-9153-56fe1a6e2b1b.png)

Is there a workaround for this issue?

Kind regards,
Vivien

**Comment by mattfrear** [comment]
Hi Vivien

I just did a search of the closed issues of this repository, and found this: https://github.com/mattfrear/Swashbuckle.Examples/issues/42. It looks like I added code which outputs nulls in version 3.11.0, so if you rollback to an earlier version of this package, say 3.10.0, then I think you'll get the behaviour you would like. 

Let me know if that works for you.

PS. This project is quite old now. Most new projects these days are using .NET Core. If you're using .NET Core then you'll want to use the .NET Core version of Swashbuckle over at Swashbuckle.AspNetCore. and the .NET Core version of my examples generator over at https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters

**Comment by mattfrear** [comment]
Hi again

Actually, I just tried my suggestion and it didn't work - bools and ints are still in the output.

However, I found a workaround. If you change your example to output an anonymous type it should work. i.e.

Instead of:
```csharp
public object GetExamples()
{
    return new ArticlePositionItem() {
        ArticleNumber = "8005",
        // etc
    }
}
```
Try:
```csharp
public object GetExamples()
{
    return new {
        ArticleNumber = "8005",
        // etc
    }
}
```

If that works for you, then please close this issue.

Matt

**Comment by vschuboth** [comment]
It works! Thank you 👍
