### ISSUE TITLE
IExamplesProvider serializer does not use ISchemaFilter

### ISSUE THREAD

**Issue by haldiggs** [mattfrear/Swashbuckle.Examples#57]
I used a SwaggerGen.ISchemaFilter to remove properties that I don't want the user seeing during object serialization.
`schema.Properties.Remove("processType");`
Then created an IExamplesProvider<> for the same object. The properties I wanted the schema filter to take out are in this object. Can someone tell me where aI have to add code to now remove these again? I cannot find anything online.

**Comment by mattfrear** [comment]
Hi Hal

Maybe you can use your SchemaFilter to add examples?

PS. this repo isn't really supported any more - Swashbuckle.AspNetCore.Filters gets my attention these days.

Matt

**Comment by haldiggs** [comment]
Thanks Matt. I'll look into it.

Hal D. on my Android

**Comment by haldiggs** [comment]
I'm actually using that package. Sorry I must have ended up in the wrong repo
