### ISSUE TITLE
Examples Stop Working with Swashbuckle v5.6.0

### ISSUE THREAD

**Issue by ntregillus** [mattfrear/Swashbuckle.Examples#8]
Love this nugget package! been working great until I upgrated to v5.6.0 and now the response examples are not loading correctly. My default serialization is getting overrwritten (defaulting back to camelCase) and all request payloads are getting wrapped in an outer object with a single "application/json" property.

![image](https://user-images.githubusercontent.com/1624697/28897238-101a175c-779d-11e7-870b-ef65f29b447e.png)

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.Examples/3.3.1

**Comment by mattfrear** [comment]
I have undone this change and released a new version, as wrapping the response in application/json mime type is the correct behaviour as per the Swagger spec.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#exampleObject

 I suspect it may be a bug in Swagger-UI that is causing it to be displayed.

Released: https://www.nuget.org/packages/Swashbuckle.Examples/3.3.3
