### ISSUE TITLE
Cannot use Swashbuckle.Examples with .NET 4.5.2

### ISSUE THREAD

**Issue by cazzoo** [mattfrear/Swashbuckle.Examples#9]
Hello there.
I tried to use the package "as-is" in my current MVC web application and it seems not to be able to install because of the fact I'm using .NET framework 4.5.2.
Here is the complete message : 

> Could not install package 'Swashbuckle.AspNetCore.Examples 2.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

If it is possible to update the package to allow this version of the framework that would be super nice.
Thanks

**Comment by cazzoo** [comment]
Quick update : I notice that the current required framework is 4.6.1.
Why do we require such a high framework ?

**Comment by mattfrear** [comment]
Hi,

That is possibly a mistake by me. I will try to lower the package
requirements sometime in the next few days for you.

Matt

-- 
*Matt Frear*
matt.frear@gmail.com

**Comment by mattfrear** [comment]
Hang on - this repo is for the Swashbuckle.Examples project, which should be compatible with 4.0 and up.

Looking at your error message, you are trying to install `Swashbuckle.AspNetCore.Examples` which is my .NET Core port of this project. 

You need to install Swashbuckle.Examples instead.

**Comment by cazzoo** [comment]
That totally true. Forgive me for this one. 
Just installed Swashbuckle.Examples 3.3.1 without any harm.

Thanks
